name: Deploy WordPress to DigitalOcean

on:
  push:
    branches:
      - staging  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Copy SSH Key to Droplet
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ~/.ssh/id_rsa staging@64.226.74.83:~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          user: staging
          your_droplet_ip: 64.226.74.83

        
      - name: Clone WordPress Repository
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} staging@64.226.74.83 "git clone https://github.com/nwekejoshua/joshua-wordpress.git /var/www/html/"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          your_repository_url: https://github.com/nwekejoshua/joshua-wordpress.git
          user: staging
          your_droplet_ip: 64.226.74.83

      - name: Configure WordPress
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} staging@64.226.74.83 "sudo cd /var/www/html/joshua-wordpress && cp wp-config-sample.php wp-config.php"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} staging@64.226.74.83 "sudo cd /var/www/html/joshua-wordpress && sed -i 's/joshua_wordpress/joshua_wordpress/g' wp-config.php"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} staging@64.226.74.83 "sudo cd /var/www/html/joshua-wordpress && sed -i 's/joshua/joshua/g' wp-config.php"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} staging@64.226.74.83 "sudo cd /var/www/html/joshua-wordpress && sed -i 's/1234/1234/g' wp-config.php"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          user: staging
          your_droplet_ip: 64.226.74.83
          your_db_name: joshua_wordpress
          your_db_user: joshua
          your_db_password: 1234

      - name: Set Permissions
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your_droplet_ip "chown -R www-data:www-data /var/www/html/wordpress"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your_droplet_ip "chmod -R 755 /var/www/html/wordpress"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          user: staging
          your_droplet_ip: 64.226.74.83

      - name: Enable Apache Rewrite Module
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} staging@64.226.74.83 "a2enmod rewrite"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          user: staging
          your_droplet_ip: 64.226.74.83

      - name: Restart Apache
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} staging@64.226.74.83 "systemctl restart apache2"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          user: staging
          your_droplet_ip: 64.226.74.83
